#!/usr/bin/env python
# -*- coding: utf-8 -*-

# A munin plugin for tracking IMAP message quantities.  Tuned specifically
# for gmail, but it can be widged to work with other IMAP servers too.

# To use:
#  1) Copy plugin-conf.d_inboxcount to /etc/munin/plugin-conf.d/inboxcount
#  2) Put your username/password/hostname stuff there.
#     (Note: chmod 600 and chown munin.munin this file)
#  3) Create some symlinks to inboxcount from:
#     /etc/munin/plugins/inboxcount
#     /etc/munin/plugins/inboxcount_sendrate
#     /etc/munin/plugins/inboxcount_spamrate
#     /etc/munin/plugins/inboxcount_spamometer
#     (Note: The last three there only work with Gmail at this time.)
#  4) Restart munin-node and enjoy!

# Inspired by:
# http://mail.python.org/pipermail/python-list/2003-February/189850.html

# Ryan Tucker <rtucker@gmail.com>

import imaplib
import os
import sys

myname = os.path.split(sys.argv[0])[-1]
myroot = myname.split('_')[0]

if len(myname.split('_')) == 1:
    mytype = 'inboxcount'
else:
    mytype = myname.split('_')[1]

outfile = '/var/run/munin/' + myroot

try:
    username = os.environ['username']
    password = os.environ['password']
    hostname = os.environ['hostname']
except KeyError:
    sys.stderr.write('Please configure this plugin!\n')
    sys.exit(1)

class ImapCheckResult:
    def __init__(self):
	self.total_messages = 0
	self.unseen_messages= 0
	self.deleted_messages = 0
	self.answered_messages = 0
	self.seen_messages = 0
    
    def __repr__(self):
	return "total.value %i\nunseen.value %i\nseen.value %i\ndeleted.value %i\nanswered.value %i" % (self.total_messages, self.unseen_messages, self.seen_messages, self.deleted_messages, self.answered_messages)

def do_imap_login(host, user, passwd):
    imap = imaplib.IMAP4_SSL(host)
    imap.login(user, passwd)
    return imap

def check_imap_folder(imap, foldername):
    result = ImapCheckResult()
    typ, data = imap.select(foldername, 1)
    result.total_messages = int(data[0])
    typ, data = imap.search(None, 'UNSEEN')
    result.unseen_messages = len(data[0].split())
    typ, data = imap.search(None, 'SEEN')
    seen_messages_tmp = len(data[0].split())
    typ, data = imap.search(None, 'DELETED')
    result.deleted_messages = len(data[0].split())
    typ, data = imap.search(None, 'ANSWERED')
    result.answered_messages = len(data[0].split())
    # fudge seen messages to remove deleted messages
    if seen_messages_tmp > result.deleted_messages:
      result.seen_messages = seen_messages_tmp - result.deleted_messages
    else:
      result.seen_messages = 0
    return result

def print_config(type='inboxcount', hostname='', spamminimum=1):
    # outputs the configuration for a given instance
    if type == 'inboxcount':
        if hostname == 'hiveminder.com':
            print """graph_title Hiveminder States for %s
graph_args --base 1000 -l 1 --logarithmic
graph_vlabel tasks
graph_category User
graph_info Tasks in my Hiveminder todo list
unseen.label Active tasks
unseen.info All unhidden tasks
duetoday.label Tasks due today
duetoday.info Tasks which are due today
overdue.label Overdue tasks
overdue.info Due date is before today
hidden.label Hidden tasks
hidden.info Tasks hidden until some future date""" % username
        else:
            print """graph_title IMAP Message States for %s
graph_args --base 1000 -l 0
graph_vlabel quantity
graph_category User
graph_info This graph indicates the number and state of messages in my inbox.
unseen.label Unseen Messages
unseen.info Messages that are unread (fresh and bold).
seen.label Seen Messages
seen.info Messages that have been read but haven't yet been selected for archiving.
deleted.label Deleted Messages
deleted.info Messages in queue to be archived, awaiting an EXPUNGE command.
answered.label Answered Messages
answered.info Messages to which a reply has been sent.
starred.label Starred Messages
starred.info Messages marked for handling in the future.""" % username
    elif type == 'spamrate':
        print """graph_title Spam Infiltration Rate
graph_args --base 1000 -l 0
graph_vlabel Rate
graph_category User
graph_info Displays the rate at which new spam are arriving per second
graph_period minute
spamrate.label Spam infiltration
spamrate.info Rate of spam infiltration
spamrate.type DERIVE
spamrate.min 0"""
    elif type == 'spamometer':
        print """graph_title Spamometer
graph_args --base 1000 -l %i --logarithmic
graph_vlabel Spams
graph_category User
graph_info Shows the total count of spam in my spam trap.
spamometer.label Spamometer
spamometer.info Total spam in spam purgatory.""" % spamminimum
    elif type == 'sendrate':
        print """graph_title E-mail Send Rate
graph_args --base 1000 -l 0
graph_vlabel e-mails sent per second
graph_category User
graph_info A visual representation of how many e-mails I'm sending per second
graph_period minute
sendrate.label Send Rate
sendrate.info The rate at which I am sending e-mail
sendrate.type DERIVE
sendrate.min 0"""

def send_cached_value(type):
	infd = open(outfile, 'r')
	for i in infd.readlines():
		if i.split()[0] == type + '.value':
			return i

def main():
    if len(sys.argv) > 1 and sys.argv[1] == 'config':
        print_config(mytype, hostname)
    else:
      imap = do_imap_login(hostname, username, password)
      result = check_imap_folder(imap, "INBOX")
      print result
      if hostname == 'imap.gmail.com':
        senttotal = int(imap.select('Sent', 1)[1][0]) + int(imap.select('[Gmail]/Sent Mail', 1)[1][0])
        starredtotal = int(imap.select('[Gmail]/Starred', 1)[1][0])
        spamtotal = int(imap.select('[Gmail]/Spam', 1)[1][0])
        print 'starred.value %i' % starredtotal
        outfd = open(outfile, 'w')
        outfd.write('sendrate.value %i\nspamometer.value %i\nspamrate.value %i\n' % (senttotal, spamtotal, spamtotal))
        outfd.close()
      elif hostname == 'hiveminder.com':
        print 'duetoday.value %i' % int(imap.select('/Saved searches/Due Today', 1)[1][0])
        print 'overdue.value %i' % int(imap.select('/Saved searches/Overdue Tasks', 1)[1][0])
        print 'hidden.value %i' % int(imap.select('/Saved searches/Hidden Tasks', 1)[1][0])
      else:
        print 'starred.value 0'
      imap.logout()
      if 'arduino' in os.environ.keys():
        # experimental arduino flasher support!
        # expects four bytes, FXXX, where XXX is how "furious" the flashing
        # of a led should be.
        # i'd say that if i have more than 25 unread mails, it should be
        # really furious.
        furiousness = min(result.unseen_messages/25.0, 1) * 100
        import serial
        ser = serial.Serial(os.environ['arduino'], 9600)
        ser.write('F%03i' % furiousness)

if __name__ == '__main__':
    if mytype == 'inboxcount':
        main()
    else:
        if len(sys.argv) > 1 and sys.argv[1] == 'config':
            if mytype == 'spamometer':
                minimum_string = send_cached_value(type='spamometer').split(' ')[1]
                minimum_number = 10**(len(minimum_string)-3)
                if minimum_number < 1:
                    minimum_number = 1
                print_config(mytype, spamminimum=minimum_number)
            else:
                print_config(mytype)
        else:
            print send_cached_value(mytype)

